TheSeekerGame/TheSeeker

README.md

seems like the github pages site got changed

fix broken doc links

---

assets/levels.assets.ron
assets/levels/level.dev.ldtk
assets/levels/level.dev/png/Level_0__Background.png
assets/levels/level.dev/png/Level_0__FarBackground-int.png
assets/levels/level.dev/png/Level_0__FarBackground.png
assets/levels/level.dev/png/Level_0__IciclesOverlay.png
assets/levels/level.dev/png/Level_0__Main-int.png
assets/levels/level.dev/png/Level_0__Main.png
assets/levels/level.dev/png/Level_0__MainOverlay.png
assets/levels/level.dev/png/Level_0__MiddleBackground-int.png
assets/levels/level.dev/png/Level_0__MiddleBackground.png
assets/levels/level.dev/png/Level_0__NearBackground-int.png
assets/levels/level.dev/png/Level_0__NearBackground.png
assets/levels/level.dev/png/Level_0__SnowOverlay.png
assets/levels/level.dev/png/Level_0_bg.png
game/src/level.rs

run with `--features dev` to use the smaller level, for development perf reasons.

added dev level

---

doc/src/tech/anim-ref.md
doc/src/tech/anim.md
doc/src/tech/script-ref.md
engine/src/animation.rs
engine/src/assets/animation.rs
engine/src/assets/script.rs
engine/src/data.rs
engine/src/lib.rs
engine/src/script.rs
engine/src/script/common.rs
engine/src/time.rs

This PR description gives a brief showcase of all the new features. Please read the docs in the book for more info! Everything is documented there!
You no longer have to mentally keep track of all your frame numbers! No more hardcoded magic constants!
Give your frames names/labels, called "bookmarks", and then all the scripting can reference those!
If you want to reorganize your sprite sheets at any point, now you only have to change one number in one place.
```toml
[frame_bookmarks]
my_loop_start = 10
my_loop_end = 19
[[script]]
run_at_frame = "my_loop_end"
action = "SetFrameNext"
to_bookmark = "my_loop_start"
```
You can now easily schedule a script action to run on many different frames/ticks/times/whatever, without having to copy-paste / duplicate it.
```toml
[[script]]
run_at_frame = …
```

Lots of scripting improvements!

---

game/src/game/enemy.rs

adds condition for ai to account for knockback

knockback ai fix

---

game/src/game/enemy.rs
game/src/game/player.rs
game/src/game/wall.rs

Enemies and Player collide, Player can fall through enemies from the top, while inside player can move/collisions with enemies are disabled.

Player and Enemy collisions

---

game/src/game/enemy.rs

`EnemySpawner` only spawns enemies when the player is further away than `EnemySpawner::RANGE`

player distance condition added to enemy spawn

---

engine/src/physics.rs
game/src/game/enemy.rs
game/src/game/player/player_behaviour.rs

Player now only ignores collisions with enemies it is already inside.

enemy and player collision avoidance is more granular

---

game/src/game/attack/mod.rs

Flashes white on damage for 8 ticks/1 animation frame.

Attack damage flash

---

game/src/ui.rs
game/src/ui/kill_counter.rs

Implements the kill counter ui.

kill counter ui

---

Cargo.toml
assets/animations/player/movement/Run.anim.toml
assets/animations/player/sword/BasicIdle.anim.toml
engine/src/animation.rs
engine/src/assets.rs
engine/src/assets/script.rs
engine/src/audio.rs
engine/src/audio/mixer.rs
engine/src/lib.rs
engine/src/script.rs
engine/src/script/common.rs
game/src/audio.rs
game/src/main.rs

Supersedes #20 
Everything is in place and it *should* work, but it is missing the "reset" call to set the audio delay (so that we don't drop sounds), so it drops sounds. 
TODO: I need to test this on a system where the game runs with adequate performance (my GPU driver doesn't seem to be cooperating at the moment). If you have a fast PC, it *might* just work. I don't know until I test.
Feel free to merge it anyway (pending any code review comments). I am confident in the code that is part of this PR, and I can add the reset call in a future PR to make it behave reliably.

Audio: Take 2!

---

game/src/game/player/player_behaviour.rs

fix friction added while not moving

---

game/src/game/player/player_behaviour.rs

Order player_pushback after player_sliding and before player_jump.

Walljump fix

---

game/src/game/player/player_anim.rs

fix: fall anim only when velocity negative

---

assets/animations.assets.ron
assets/animations/spider/Sparks.anim.toml
engine/src/gent.rs
game/src/game/attack/mod.rs
game/src/game/enemy.rs
game/src/game/player/mod.rs

feat: sparks on enemy hit

---

game/src/camera.rs

I did some refactoring of the camera.rs file while I was digging through the code and figuring out how it all works. If this makes the code too much of a pain to review, let me know and I can break the refactoring steps into smaller PRs.

119 camera scaling issue

---

game/src/game/enemy.rs
game/src/game/physics.rs

Changed enemy behavior to match #116

New spiders

---

game/src/game.rs
game/src/game/xp_orbs.rs

Xp Orbs that spawn when enemies die; float upwards for 4.0s, before moving towards the player and disappearing when in contact.

XP Orb Implementation

---

Cargo.toml
assets/shaders/enemy_hp.wgsl
game/src/dev.rs
game/src/graphics/enemy_hp.rs
game/src/main.rs

As part of https://github.com/TheSeekerGame/TheSeeker/issues/124, This adds the animated white damage indication to the enemy health bars.

Enemy HP Bar Damage Effect

---

game/src/ui/ability_widget.rs

Fixes #115
- Updated the cooldown color to a yellow shade and alpha to a higher value to try making them more legible.
- Fixed a typo in the comments and some clippy lints.

Darker Cooldown UI

---

game/src/game/enemy.rs

unique ranges for melee and ranged enemies

Enemy ranges split

---

assets/animations/spider/big/tier1/Sparks.anim.toml
game/src/game/enemy.rs

Fixes #171 
- Removed Spark sounds on Enemy spawns.
- Fixed lints and removed unnecesary code and comments from `enemy.rs`.

Fix Sparks Sound

---

game/src/game/player/player_behaviour.rs

Fixes #175 
- Before this change, the code was always storing the TOI of the player fall in `player_grounded`. That made the `!is_falling && time_of_impact != 0.0` condition true in situations where the player wasn't falling (yet the TOI had some value), and so the player position was being adjusted higher than it should be and it produced a "constantly falling while moving" animation.
- After the change, the TOI variable gets a value different than zero only when the grounded threshold is exceeded.

Fixes player constantly falling while walking

---

assets/animations/merchant/Idle.anim.toml
game/src/game/merchant.rs
game/src/game/switches.rs

Fixes #180 
- Sets "PlayerNearby" slot on the Merchant's animation script to determine the animation frames to be played (idle/playing instrument).
- Minor refactors in the Merchant module.
- Optimized the switching mechanic.

Merchant Proximity to Player

---

game/src/ui/skill_toolbar.rs

Fixes #192 
- Updated skill toolbar styles to fit the updated UI assets.
- Removed superfluous nodes and styles.
- Fixed some lints and formatted code.

Improved Skillbar

---

game/src/game/player/mod.rs
game/src/game/player/player_action.rs
game/src/ui/controls_overlay.rs

- Implemented key mappings for gamepad support.
- Adds a new module for PlayerAction to extract some code out of the main player module.

Basic Gamepad Support
