TheSeekerGame/TheSeeker

game/src/game/attack/mod.rs
game/src/game/enemy.rs
game/src/game/player.rs

different deaggro behavior, faster transitions to defense/melee attack on melee range, placeholder collisions between enemy and player (only changed collision layers, current strategy for both player and enemy dont account for moving things?)

Enemy state machine adjustment

---

game/src/game/player/mod.rs
game/src/game/player/player_anim.rs
game/src/game/player/player_behaviour.rs

Refactors player.rs into a full module and splits player behaviour and player animation plugins into their own files.
Player.rs was getting a bit monolithic and this is the best time to make the change while fewer player related things are in progress.
It will also make implementing player abilities easier.

refactor player.rs into a full module

---

game/src/game/attack/mod.rs
game/src/game/player/mod.rs
game/src/game/player/player_behaviour.rs
game/src/graphics/dmg_numbers.rs

Implements critical strikes, and the new Focus ability, which will double your damage, but has a 10 second cooldown.
If focus is active during a critical strike, it can be re-activated with no cooldown.

focus_ability

---

Cargo.toml
engine/src/input.rs
engine/src/lib.rs
engine/src/time.rs
game/src/game/player/mod.rs

This pr adapts the pr from LWIM which fixes the behavior of `just_pressed` and `just_released` in `FixedUpdate` https://github.com/Leafwing-Studios/leafwing-input-manager/pull/522  to work with our `GameTickUpdate` schedule. It relies on a branch of LWIM with an older version of the fix applied to the bevy 0.13 compatible branch, and re-implements the `InputManagerPlugin` to add the pressed state updating systems to the correct schedules and sets when building.

Fix `just_pressed` in `GameTickUpdate`

---

game/src/game/gentstate.rs
game/src/game/player/mod.rs
game/src/game/player/player_behaviour.rs

Attack now doesn't continuously trigger if held down, but if an attack input is pressed during the later half of the animation another attack will be queued up immediately on transition.

immediately follow attack on new press

---

assets/player.cfg.toml
game/src/game/player/mod.rs
game/src/game/player/player_behaviour.rs

Technical Summary:
- Added JumpCount(u8) Component for tracking available jumps. Added to player on setup_player.
- JumpCount is reset in player_grounded, player_sliding.
- when Jumping in player_falling, checks for JumpCount field > 0; if valid jumps and decrements by 1
Gameplay Mechanics Related: 
The Air Jump functions the same as the normal grounded jump, with controlled jump height - so unlike in Hollow Knight, where the double jump gives a consistent upwards burst.
Typical platformer mechanic is maintained of only having a single jump when walking of a platform, with respect for coyote time of course :)
The same pertains to jumping when wall-sliding, however jumping from the wall counts as your double jump - since the state transitions into Falling(?). Walking off of a wall allows …

Double Jump Implementation

---

game/src/game/attack/mod.rs
game/src/game/enemy.rs
game/src/game/player/mod.rs
game/src/game/player/player_behaviour.rs

Implementation for "Chill Effect" with a general extendable system for Status Modifiers on the player.
Currently only allows for a single type of active status modifier; new applications replace the old one.
PlayerStats added; copies data from PlayerConfig and adds StatusModifiers.
Changed player_move code to read from PlayerStats instead - any additional "status impairable stats" will need to do the same.

Chill Effect Implementation

---

game/src/game/player/mod.rs
game/src/game/player/player_behaviour.rs

Implementation for an After Image while Dashing.
The "Dash Icon" is spawned at the player position every frame while dashing, which gives good coverage. Depending on changes to the tick-rate, a more nuanced effect with interpolation may be preferred.
Icons fade out quickly. also works with Stealth; The Alpha of the Icon image is set lower if stealthed, giving a good effect imo.
Code is currently in player_behaviour.rs and player/mod.rs so it's close to the dash code; 
depending on further features (like hit-sparks), refactoring it to a file named something like player_vfx.rs may make for a cleaner code structure.

Dash After-Image implemented

---

doc/src/tech/anim-ref.md
doc/src/tech/script-ref.md
engine/src/animation.rs
engine/src/assets/animation.rs
engine/src/assets/script.rs
engine/src/script.rs
engine/src/script/common.rs

New features:
- add `if_runcount_is_not` and `if_frame_is_not` parameters (for "not equals" checking)
- add `if_oldanim_frame_*` parameters
- allow you to do things based on where the previously-playing animation left off
- use in combination with `if_previous_script_key`
Internal changes:
There is now a general "data carry-over" mechanism in the script runtime, allowing the previously-running script to prepare some data to be made available to the newly-starting script.
For now, this is only used for the "old animation frame index" feature.
But in the future, we could use it to easily add other pieces of data that should be retained from previously-running scripts, should we want to.

Animation/Scripting Improvements

---

assets/animations/spider/Decay.anim.toml
doc/src/tech/anim-ref.md
engine/src/animation.rs
engine/src/assets/animation.rs
game/src/game/enemy.rs

Fixes #114 
-  Increased `anim.spider.Decay` frame time
- Added an optional parameter to `SetTicksPerFrame` script action to reset the current frame tick progress
- Added an Enemy system to control decay frame time using sprite's calculated view visibility
This essentially halts the decay animation if the enemy is visible.

Spider decay adjustment

---

Cargo.toml
game/src/game/player/mod.rs
game/src/game/player/player_behaviour.rs
game/src/graphics/dmg_numbers.rs

Fixes #122
- `DmgNumber` now gets cleaned up between app state changes (fixes `DmgNumber` related panic)
- Changed `PlayerStats` type from `Resource` into `Component`. (fixes slow stats persisting after restart)
This also includes a warning clean up + globally ignore `type_complexity` setting in Cargo.toml which should reduce the project's warning total.

Game restart bug fixes

---

assets/player.cfg.toml
engine/src/physics.rs
game/src/game/attack/arc_attack.rs
game/src/game/attack/mod.rs
game/src/game/enemy.rs
game/src/game/gentstate.rs
game/src/game/player/mod.rs
game/src/game/player/player_anim.rs
game/src/game/player/player_behaviour.rs
game/src/game/player/player_weapon.rs

Fixes #137
- Added `PlayerWeapon` plugin that manages swapping between the Sword and the Bow weapons.
- Added a new keybind (H key) that swaps weapons for the Player.
- While using the Bow weapon, the Player now shoots arrows when pressing the attack key.
- Player will always face an enemy when holding the Bow weapon.
- Added configurable velocity, knockback and base damage variables for the arrows shot by the Player.
- FIxed a few typos in comments.

Bow Attack + Weapon Swap

---

assets/animations.assets.ron
assets/animations/player/sword/DashDownStrike.anim.toml
assets/player.cfg.toml
game/src/game/player/mod.rs
game/src/game/player/player_anim.rs
game/src/game/player/player_behaviour.rs
game/src/ui/skill_toolbar.rs

addresses #125 
Adds a downward dash ability when pressing the 's' key when activating a dash.
The downward dash uses a different animation.
When colliding with an enemy or a wall, a strike animation is played, as well as a damage collider. The camera also shakes on impact.
If there is no collision, there is no final strike animation, and no damage collider.
The main changes involved adding new fields to the "Dashing" state's struct to keep track of what type of dash is happening, and adding a new "DashStrike" state to handle the strike attack state. Throughout the code, there are several references that assumed the configuration values for a dash were constant. These changed to use the dash's type to either use the "horizontal" dash config, or the "downward" dash config. 
The animation …

Add downward dash ability

---

game/src/graphics/player_hp.rs

Change Vignette color on Low HP #146
When player's health is reduced to 25 percent or below, the vignette begins to oscillate with a mild red and fuller red. if hp increases back to above 25 percent, the normal vignette is restored.

Change Vignette color on Low HP

---

game/src/game/player/player_behaviour.rs

- Added system ordering to `bow_auto_aim` so it runs after `player_move` (which handles the player facing) to attempt to fix the regression in the bow auto aim feature.

Fix Bow Auto-Aim Feature

---

assets/animations.assets.ron
assets/animations/player/hammer/BasicAir.anim.toml
assets/animations/player/hammer/BasicIdle.anim.toml
assets/player.cfg.toml
game/src/game/attack/mod.rs
game/src/game/player/mod.rs
game/src/game/player/player_anim.rs
game/src/game/player/player_behaviour.rs
game/src/game/player/player_weapon.rs
game/src/ui/controls_overlay.rs

Fixes #154 
- Reworked the `PlayerWeapon` plugin to include "combat styles" (melee/ranged) and differentiate the currently selected melee and ranged weapons.
- Implemented Hammer weapon with attacks and animations.
- Added a configurable movement slowdown to the Player while attacking with the Hammer.
- Added configurable base damage for both the Sword and Hammer weapons.
- Added configurable pushback settings for both the Sword and Hammer weapons.
- Added configurable screenshake settings for the Hammer weapon and a default one for the rest.
- Added and updated UI elements to the controls overlay to better explain the weapon swapping actions.
- Fixed several lints and typos.

Hammer Weapon Set

---

engine/src/gent.rs
game/src/game/enemy.rs
game/src/game/player/mod.rs

Fixes by requiring despawn to happen after the gameover screen is spawned in.

Game Over screen Bug fix #158

---

game/src/ui/controls_overlay.rs

Fixes #179 
- Updated controls popup notification styles to show it on the screen properly.
- Display the controls popup notification only when starting a new game from the main menu.

Update Controls Hint

---

game/src/game/attack/mod.rs

Fixes #177 
- Ordered `determine_attack_targets` before transform propagation so attack intersections are calculated before entities were translated on this frame.

Attempts to fix Attack hits not being registered

---

assets/animations/spider/big/tier1/Sparks.anim.toml
assets/audio.assets.ron
assets/audio/attack/HammerImpact1.flac
assets/audio/attack/HammerImpact2.flac
assets/audio/attack/HammerImpact3.flac
assets/audio/attack/HammerImpact4.flac
assets/audio/attack/SwordImpact1.flac
assets/audio/attack/SwordImpact2.flac
assets/audio/attack/SwordImpact3.flac
assets/audio/attack/SwordImpact4.flac
assets/audio/fx/PlayerGetsDamaged1.flac
assets/audio/fx/PlayerGetsDamaged2.flac
assets/audio/fx/PlayerGetsDamaged3.flac
assets/audio/fx/PlayerGetsDamaged4.flac
game/src/game/enemy.rs
game/src/game/player/player_weapon.rs

Fixes #182 
- Added hit sound assets for each weapon type. A generic one was also kept in case the weapon-based flags are not set.
- Implemented said placeholder sounds based on the current weapon that the player is wielding.
- Renamed "Hit" slot in `Sparks.anim.toml` to "AttackHit".
- Optimized `enemy_sparks_on_hit_animation` to run only when there are relevant events to read.
- Added SFX assets for player receiving damage.

Add Weapon Dependent Hit Sfx

---

doc/src/tech/script-ref.md
engine/src/assets/script.rs
engine/src/audio.rs
engine/src/audio/mixer.rs
engine/src/script/common.rs

This PR adds some new features to audio scripting:
* The `PlayBackgroundAudio` action now has a `loop` parameter, which can make the audio loop from the beginning instead of stopping when finished.
* The `PlayAudio` and `PlayBackgroundAudio` now support a `label` parameter, which can be used to associate the sound with a string label. This is useful for identifying sounds and for grouping related sounds.
* New `StopAudio` and `StopBackgroundAudio` actions for stopping sounds that might be currently playing. The selection of which sounds to stop can be done by label. It is also possible to choose whether only sounds that were started by the current run of the current script will be considered, or all sounds.
Examples:
```toml
[[script]]
run_at_tick = 0
action = "PlayAudio"
asset_key = …
```

Audio improvements: support labeling, stopping, looping

---

game/src/game/player/mod.rs

health cost is equal to the current number of stacks, applies on every damage instance if player has FrenziedAttack passive

added health cost on FrenziedAttack hit

---

game/src/game/enemy.rs
game/src/game/merchant.rs
game/src/game/switches.rs
game/src/game/xp_orbs.rs
game/src/game/yak.rs

Fixes #188 
- Switches render behind walls properly.
- Merchant and yak now render behind the player.
- Dead enemies are now rendered behind all other creatures.
- Xp orbs are now rendered over walls (but behind the player).
- Enemy projectiles are now rendered over walls (and will stop outputting visibility related warnings).
- Spider enemies are z sorted based on their `Role` (melee>ranged) and `Tier` (higher tier>lower tier).

Layer Ordering Fixes

---

assets/animations/player/hammer/BasicAir.anim.toml
assets/animations/player/sword/BasicAir.anim.toml
game/src/game/attack/mod.rs
game/src/game/player/mod.rs
game/src/game/player/player_anim.rs
game/src/game/player/player_behaviour.rs
game/src/game/player/player_weapon.rs

Fixes #153 
- Updated animation scripts to support downward attacks.
- Implemented downward attacks that pushes the player upwards on hit and resets the jump counter.
- Refactored `player_whirl` code to fix lints and for future proofing.

Downward Attack
